FROM --platform=$BUILDPLATFORM rust:alpine3.15 AS rustbuilder

WORKDIR /app

ENV GRPC_HOST=0.0.0.0:50053

RUN apk upgrade --update-cache --available && \
	apk add npm gcc cmake make g++

RUN npm install @a11ywatch/protos

COPY . .

RUN cargo install --no-default-features --path .

FROM node:18.10-alpine AS BUILD_IMAGE

WORKDIR /app

COPY package*.json ./

RUN npm ci

FROM node:18.10-alpine

WORKDIR /usr/src/app

RUN apk upgrade --update-cache --available && \
	apk add openssl

COPY --from=BUILD_IMAGE /app .
COPY --from=rustbuilder /usr/local/cargo/bin/health_client /usr/local/bin/health_client
COPY . .

CMD ["node_modules/ts-node-dev/lib/bin.js", "--transpile-only", "src/server.ts"]