FROM node:14.7.0-alpine AS BUILD_IMAGE

WORKDIR /app

COPY package*.json ./

RUN npm ci

FROM node:14.7.0-slim

WORKDIR /usr/src/app

COPY --from=BUILD_IMAGE /app .
COPY . .

CMD ["node_modules/ts-node-dev/lib/bin.js", "--transpile-only", "src/server.ts"]